# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'
  # Pods for RxSwift_Demo

  target 'RxSwift_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwift_DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
